# Generated by Django 3.2.11 on 2022-01-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous_letters', '0003_auto_20220125_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
