# Generated by Django 3.2.11 on 2022-01-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous_letters', '0004_auto_20220125_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
